<?php

    $razonSocial = $_POST['razonSocial'];

?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        * {
            max-width: 1000px;
        }
    </style>
</head>
<body>
    <h2>Politica de Cookies</h2>
<p style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;margin-top:7.5pt;margin-right:0cm;margin-bottom:7.5pt;margin-left:0cm;background:white;vertical-align:baseline;'><span style='font-family:"Arial",sans-serif;color:black;'>Nuestra web utiliza cookies propias y de terceros con la finalidad de mejorar los servicios de navegaci&oacute;n. Usted puede rechazar o deshabilitar el uso de las cookies a trav&eacute;s de las opciones de su navegador, tal y como se indica en el presente documento.</span></p>
<p style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;margin-top:7.5pt;margin-right:0cm;margin-bottom:7.5pt;margin-left:0cm;background:white;vertical-align:baseline;'><span style='font-family:"Arial",sans-serif;color:black;'>Las cookies son ficheros de texto que el sitio web env&iacute;a al navegador y que se almacenan en el equipo del usuario con la finalidad de almacenar y recuperar informaci&oacute;n sobre la navegaci&oacute;n que se realiza desde ese equipo (ordenador, tel&eacute;fono m&oacute;vil, tablet etc&hellip;).</span></p>
<p style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;margin-top:7.5pt;margin-right:0cm;margin-bottom:7.5pt;margin-left:0cm;background:white;vertical-align:baseline;'><span style='font-family:"Arial",sans-serif;color:black;'>En funci&oacute;n de su permanencia y de la finalidad para la que se utilicen los datos obtenidos a trav&eacute;s de las cookies, existen varios tipos.</span></p>
<p style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;margin-top:7.5pt;margin-right:0cm;margin-bottom:7.5pt;margin-left:0cm;background:white;vertical-align:baseline;'><span style='font-family:"Arial",sans-serif;color:black;'>As&iacute;, inicialmente las cookies pueden ser &ldquo;de sesi&oacute;n&rdquo;, que expiran cuando el usuario acaba la navegaci&oacute;n y cierra el explorador, y &ldquo;permanentes&rdquo; que expiran cuando hayan cumplido la funci&oacute;n para que est&aacute;n concebidas o cuando el usuario las borra.</span></p>
<p style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;margin-top:7.5pt;margin-right:0cm;margin-bottom:7.5pt;margin-left:0cm;background:white;vertical-align:baseline;'><span style='font-family:"Arial",sans-serif;color:black;'>Igualmente, dependiendo de la finalidad para la que se utilizan, las cookies pueden ser:</span></p>
<p style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;margin-top:7.5pt;margin-right:0cm;margin-bottom:7.5pt;margin-left:0cm;background:white;vertical-align:baseline;'><span style='font-family:"Arial",sans-serif;color:black;'>Cookies anal&iacute;ticas.- Recogen informaci&oacute;n para evaluar el uso que usted hace de la Web y la actividad general de la misma. La anal&iacute;tica de la Web es la medida, recolecci&oacute;n, an&aacute;lisis y creaci&oacute;n de informes de los datos de Internet con el prop&oacute;sito de entender y optimizar el uso de sitio Web.</span></p>
<p style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;background:white;vertical-align:baseline;'><span style='font-family:"Arial",sans-serif;color:black;'>Cookies sociales.- Las cookies sociales son necesarias para las&nbsp;</span><span style="color:black;"><a href="https://bsgspain.es/gestion-de-redes/" title="redes sociales"><span style='font-family:"Arial",sans-serif;color:black;border:none windowtext 1.0pt;padding:0cm;'>redes sociales</span></a></span><span style='font-family:"Arial",sans-serif;color:black;'>&nbsp;externas (Facebook, Google, Twitter, Pinteres,Discus, etc&hellip;). Su funci&oacute;n es controlar la interacci&oacute;n con los widgets sociales dentro de la p&aacute;gina.</span></p>
<p style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;background:white;vertical-align:baseline;'><span style='font-family:"Arial",sans-serif;color:black;'>Cookies de afiliados.- Permiten hacer un seguimiento de las visitas procedentes de otras Webs, con las que <strong><?php echo $razonSocial ?></strong> tiene un contrato de afiliaci&oacute;n.</span></p>
<p style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;background:white;vertical-align:baseline;'><span style='font-family:"Arial",sans-serif;color:black;'>Cookies de&nbsp;</span><span style="color:black;"><a href="https://bsgspain.es/publicidad-online/" title="publicidad"><span style='font-family:"Arial",sans-serif;color:black;border:none windowtext 1.0pt;padding:0cm;'>publicidad</span></a></span><span style='font-family:"Arial",sans-serif;color:black;'>&nbsp;y comportamentales.- Recogen informaci&oacute;n sobre sus preferencias y elecciones personales en este sitio Web. Permiten adecuar el contenido de la&nbsp;</span><span style="color:black;"><a href="https://bsgspain.es/publicidad-online/" title="publicidad"><span style='font-family:"Arial",sans-serif;color:black;border:none windowtext 1.0pt;padding:0cm;'>publicidad</span></a></span><span style='font-family:"Arial",sans-serif;color:black;'>&nbsp;para que esta sea relevante para el usuario y para evitar mostrar anuncios que el usuario ya haya visto.</span></p>
<p style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;margin-top:7.5pt;margin-right:0cm;margin-bottom:7.5pt;margin-left:0cm;background:white;vertical-align:baseline;'><span style='font-family:"Arial",sans-serif;color:black;'>Cookies t&eacute;cnicas.- Estrictamente necesarias para el uso de este sitio Web, permiten al usuario la navegaci&oacute;n a trav&eacute;s de la p&aacute;gina Web o aplicaci&oacute;n y la utilizaci&oacute;n de las diferentes opciones o servicios que en ella existen.</span></p>
<p style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;margin-top:7.5pt;margin-right:0cm;margin-bottom:7.5pt;margin-left:0cm;background:white;vertical-align:baseline;'><span style='font-family:"Arial",sans-serif;color:black;'>Cookies de personalizaci&oacute;n.- Son aqu&eacute;llas que permiten al usuario acceder al servicio con algunas caracter&iacute;sticas de car&aacute;cter general predefinidas en su terminal o que el propio usuario defina. Por ejemplo, el idioma, el tipo de navegador a trav&eacute;s del cual accede al servicio, el dise&ntilde;o de contenidos seleccionado, geolocalizaci&oacute;n del terminal y la configuraci&oacute;n regional desde donde se accede al servicio.</span></p>
<p style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;background:white;vertical-align:baseline;'><span style='font-family:"Arial",sans-serif;color:black;'>Cookies de terceros.- En algunas&nbsp;</span><span style="color:black;"><a href="https://bsgspain.es/diseno-web/" title="páginas Web"><span style='font-family:"Arial",sans-serif;color:black;border:none windowtext 1.0pt;padding:0cm;'>p&aacute;ginas Web</span></a></span><span style='font-family:"Arial",sans-serif;color:black;'>&nbsp;se pueden instalar cookies de terceros que permiten gestionar y mejorar los servicios ofrecidos.</span></p>
<p style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;margin-top:7.5pt;margin-right:0cm;margin-bottom:7.5pt;margin-left:0cm;background:white;vertical-align:baseline;'><span style='font-family:"Arial",sans-serif;color:black;'>Para gestionar la actividad de las cookies desde su equipo, usted puede aceptarlas expresamente, bloquearlas o eliminarlas. En caso de que no lo haga y siga navegando en la web, entenderemos que las acepta.</span></p>
<p style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;margin-top:7.5pt;margin-right:0cm;margin-bottom:7.5pt;margin-left:0cm;background:white;vertical-align:baseline;'><span style='font-family:"Arial",sans-serif;color:black;'>Para llevar a cabo la gesti&oacute;n de las cookies deber&aacute; seguir las siguientes instrucciones:</span></p>
<ul style="margin-bottom:0cm;margin-top:0cm;" type="disc">
    <li style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;color:black;background:white;vertical-align:baseline;'><span style='font-family:"Arial",sans-serif;'>Internet Explorer: Herramientas -&gt; Opciones de Internet -&gt; Privacidad -&gt; Configuraci&oacute;n.</span></li>
    <li style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;color:black;background:white;vertical-align:baseline;'><span style='font-family:"Arial",sans-serif;'>Firefox: Herramientas -&gt; Opciones -&gt; Privacidad -&gt; Historial -&gt; Configuraci&oacute;n Personalizada.</span></li>
    <li style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;color:black;background:white;vertical-align:baseline;'><span style='font-family:"Arial",sans-serif;'>Chrome: Configuraci&oacute;n -&gt; Mostrar opciones avanzadas -&gt; Privacidad -&gt; Configuraci&oacute;n de contenido.</span></li>
    <li style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;color:black;background:white;vertical-align:baseline;'><span style='font-family:"Arial",sans-serif;'>Safari: Preferencias -&gt; Seguridad.</span></li>
</ul>
<p style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;margin-top:7.5pt;margin-right:0cm;margin-bottom:7.5pt;margin-left:0cm;background:white;vertical-align:baseline;'><span style='font-family:"Arial",sans-serif;color:black;'>En cualquier caso, para obtener m&aacute;s informaci&oacute;n, puede consultar el soporte o la Ayuda del navegador.</span></p>
<p style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;margin-top:7.5pt;margin-right:0cm;margin-bottom:7.5pt;margin-left:0cm;background:white;vertical-align:baseline;'><span style='font-family:"Arial",sans-serif;color:black;'>El bloqueo del uso de cookies en su navegaci&oacute;n, puede hacer que algunos servicios o funciones del sitio web no est&eacute;n disponibles.</span></p>
<p style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;'><span style='font-family:"Arial",sans-serif;color:black;'>&nbsp;</span></p>
</body>
</html>
